### ISSUE TITLE
is there a wsdl achievement and authentication?

### ISSUE THREAD

**Issue by ponymuch** [yj7/YJSoapEngine#1]
1. a url like this:  http://*********/MapSearchService?wsdl

2.how to realize that?
        soap.authorizationMethod = SOAP_AUTH_BASIC
        soap.username = "test"
        soap.password = "123"

**Comment by yj7** [comment]
Hi,
1. a url like this: http://*********/MapSearchService?wsdl
 This kind of url should work. You may need to set actionNamespaceSlash = NO.

2.how to realize that?
soap.authorizationMethod = SOAP_AUTH_BASIC
soap.username = "test"
soap.password = "123"

Just released a new version with authentication support. Should solve your problem.

**Comment by ponymuch** [comment]
authentication support?
Could you please add this feature in to YJSoapEngine?
that's quite useful~
tks your reply.

**Comment by yj7** [comment]
I did add this feature in YJSoapEngine in the latest commit. Check it out. Refer to readme.md for more details.

Cheers!

**Comment by ponymuch** [comment]
Nice Work! ^_^ 
And is there a way to support Swift?
I got some trouble in it.
I use the bridge-header to import the ".h" file

**Comment by ponymuch** [comment]
Nice Work! Tks a lot!  ^_^
![image](https://cloud.githubusercontent.com/assets/10826321/9280549/a69ba32c-42f1-11e5-9d41-bc6b7f5a6cc1.png)

But i got this trouble in Swift....
I use the bridge-header files import the '.h' files ,there is no problem to init a YJSoapEngine() instance,but when i achieve the protocal(delegate),error occurred.

**Comment by ponymuch** [comment]
I have solved the problem,change the protocol name like this:

@protocol YJSoapEngineDelegate

@required
- (void)YJSoapEngineResult:(YJSoapEngine *)soapEngine didRecieveData:(NSString *)data inDictionary:(NSDictionary *)dataDictionary;
- (void)YJSoapEngineError:(YJSoapEngine *)soapEngine didRecieveError:(NSError *)error inDictionary:(NSDictionary *)errorDictionary;

@end
